    - name: Generate JaCoCo Badge
#      if: ${{ github.ref == 'refs/heads/master' }}
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
        badges-directory: build/reports/jacoco/test/html/badges
